CREATE SCHEMA EMPRESA;
GO

CREATE TABLE EMPRESA.DEPARTMENT(
    Dname NVARCHAR(55),
    Dnumber INT,
    Mgr_ssn VARCHAR(9), 
    Mgr_start_date DATE,

    CONSTRAINT Department_PK PRIMARY KEY(Dnumber)
)
GO

CREATE TABLE EMPRESA.EMPLOYEE(
    Fname NVARCHAR(20),
    Minit VARCHAR(1),
    Lname NVARCHAR(20),
    Ssn VARCHAR(9),
    Bdate DATE,
    Address NVARCHAR(110),
    Sex VARCHAR(1),
    Salary DECIMAL(10,2),
    Super_ssn VARCHAR(9),
    Dno INT,

    CONSTRAINT Employee_PK PRIMARY KEY (Ssn),
    CONSTRAINT Employee_FK_Super FOREIGN KEY (Super_ssn) REFERENCES EMPRESA.EMPLOYEE(Ssn),
    CONSTRAINT Employee_FK_Department FOREIGN KEY (Dno) REFERENCES EMPRESA.DEPARTMENT(Dnumber)
)
GO

ALTER TABLE EMPRESA.DEPARTMENT ADD CONSTRAINT Department_FK_Employee FOREIGN KEY(Mgr_ssn) REFERENCES EMPRESA.EMPLOYEE(Ssn);
GO

CREATE TABLE EMPRESA.DEPT_LOCATIONS(
    Dnumber INT,
    Dlocation NVARCHAR(60),

    CONSTRAINT DEPT_LOCATIONS_PK PRIMARY KEY(Dnumber, Dlocation),
    CONSTRAINT Dept_Locations_FK_Department FOREIGN KEY(Dnumber) REFERENCES EMPRESA.DEPARTMENT(Dnumber)
)
GO

CREATE TABLE EMPRESA.PROJECT(
    Pname NVARCHAR(60),
    Pnumber INT,
    Plocation NVARCHAR(60),
    Dnum INT,

    CONSTRAINT Project_PK PRIMARY KEY(Pnumber),
    CONSTRAINT Project_FK_Department FOREIGN KEY(Dnum) REFERENCES EMPRESA.DEPARTMENT(Dnumber)
)
GO

CREATE TABLE EMPRESA.WORKS_ON(
    Essn VARCHAR(9),
    Pno INT,
    Hours DECIMAL(5,2),

    CONSTRAINT Works_On_PK PRIMARY KEY(Essn, Pno),
    CONSTRAINT Works_On_FK_Project FOREIGN KEY(Pno) REFERENCES EMPRESA.PROJECT(Pnumber),
    CONSTRAINT Works_On_FK_Employee FOREIGN KEY(Essn) REFERENCES EMPRESA.EMPLOYEE(Ssn) 
)
GO

CREATE TABLE EMPRESA.DEPENDENT(
    Essn VARCHAR(9),
    Dependent_name NVARCHAR(50),
    Sex VARCHAR(1),
    Bdate DATE,
    Relationship NVARCHAR(15),

    CONSTRAINT Dependent_PK PRIMARY KEY(Essn, Dependent_name),
    CONSTRAINT Dependent_FK_Employee FOREIGN KEY(Essn) REFERENCES EMPRESA.EMPLOYEE(Ssn)
)
GO